version: '2'

services:
  dev:
    build:
      context:  ./
      dockerfile: Dockerfile.dev
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    environment:
      - PANOPTES_DEBUG=true

  stable:
    build:
      context: ./
      dockerfile: Dockerfile.stable
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}

  tests:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    command: python -m unittest discover
